import{a as g,i as u,S}from"./assets/vendor-BHdvj17y.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();let p=1;async function h(r,e){g.defaults.baseURL="https://pixabay.com";const i={key:"51707366-c8695cacd8b805538752cece0",q:`${r}`,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e};try{const s=await g.get("/api/",{params:i});p=Math.ceil(s.data.totalHits/i.per_page);const t=s.data.hits;return t&&Array.isArray(t)&&t.length>0?t:u.show({title:"❌",message:"Sorry, there are no images matching <br> your search query. Please try again!",color:"red",position:"topRight",messageColor:"white",titleColor:"white"})}catch(s){u.show({title:"Error",color:"red",position:"topRight",messageColor:"white",titleColor:"white",message:s.message})}}const l=document.querySelector(".loader"),m=document.querySelector(".gallery"),y=document.querySelector(".load-more");l&&(l.hidden=!0);const L=new S(".gallery-item a",{captionsData:"alt",captionDelay:250});function M(r){const e=E(r);m.insertAdjacentHTML("afterbegin",e),L.refresh()}function C(r){const e=E(r);m.insertAdjacentHTML("beforeend",e),L.refresh()}function $(){m.innerHTML=""}function b(r){l.hidden=!1,r>1&&l.classList.add("load-more-loader")}function w(){l.hidden=!0}function v(r){r<p?R():p&&(f(),u.info({message:"We're sorry, but you've reached the end of search results.",color:"blue",position:"topRight",messageColor:"black"}))}function A(){let e=m.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e.height*2,left:0,behavior:"smooth"})}function R(){y.classList.add("is-visible")}function f(){y.classList.remove("is-visible")}function P(r){const{webformatURL:e,largeImageURL:i,tags:s,likes:t,views:o,comments:n,downloads:q}=r;return`<li class="gallery-item">
  <a class="gallery-link" href="${i}">
    <img
      class="gallery-image"
      src="${e}"
      alt="${s}"
    />
  </a><div class="stats">
  <p class="img-rates">Likes<span>${t}</span></p>
  <p class="img-rates">Views<span>${o}</span></p>
  <p class="img-rates">Comments<span>${n}</span></p>
  <p class="img-rates">Downloads<span>${q}</span></p></div>
</li>
`}function E(r){return r.map(P).join(`
`)}const d=document.querySelector(".form");d.querySelector(".submit");const B=document.querySelector(".load-more");let a,c;d.addEventListener("submit",async r=>{if(r.preventDefault(),c=r.currentTarget.elements["search-text"].value.trim(),!c)return u.info({message:"Введіть запит",color:"red",position:"topRight",messageColor:"white",titleColor:"white"});$(),f(),a=1,b(a);try{const e=await h(c,a);e&&M(e)}catch(e){console.error(e)}w(),v(a),d.reset()});B.addEventListener("click",async r=>{a+=1,f(),b(a);try{const e=await h(c,a);C(e)}catch(e){console.error(e)}w(),images&&A(),v(a),d.reset()});
//# sourceMappingURL=index.js.map
