import{a as p,i as d,S as q}from"./assets/vendor-BHdvj17y.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();let m=1;async function y(r,t){p.defaults.baseURL="https://pixabay.com";const a={key:"51707366-c8695cacd8b805538752cece0",q:`${r}`,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};try{const o=await p.get("/api/",{params:a});m=Math.ceil(o.data.totalHits/a.per_page);const e=o.data.hits;return e&&Array.isArray(e)&&e.length>0?e:d.show({title:"❌",message:"Sorry, there are no images matching <br> your search query. Please try again!",color:"red",position:"topRight",messageColor:"white",titleColor:"white"})}catch(o){d.show({title:"Error",message:o.message})}}const c=document.querySelector(".loader"),u=document.querySelector(".gallery"),h=document.querySelector(".load-more");c&&(c.hidden=!0);const b=new q(".gallery-item a",{captionsData:"alt",captionDelay:250});function S(r){const t=v(r);u.insertAdjacentHTML("afterbegin",t),b.refresh()}function M(r){const t=v(r);u.insertAdjacentHTML("beforeend",t),b.refresh()}function T(){u.innerHTML=""}function $(){c.hidden=!1}function L(){c.hidden=!0}function w(r){r<m?B():m&&(O(),d.info({message:"We're sorry, but you've reached the end of search results.",color:"blue",position:"topRight",messageColor:"black"}))}function A(){let t=u.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t.height*2,left:0,behavior:"smooth"})}function B(){h.classList.add("is-visible")}function O(){h.classList.remove("is-visible")}function P(r){const{webformatURL:t,largeImageURL:a,tags:o,likes:e,views:s,comments:i,downloads:E}=r;return`<li class="gallery-item">
  <a class="gallery-link" href="${a}">
    <img
      class="gallery-image"
      src="${t}"
      alt="${o}"
    />
  </a><div class="stats">
  <p class="img-rates">Likes<span>${e}</span></p>
  <p class="img-rates">Views<span>${s}</span></p>
  <p class="img-rates">Comments<span>${i}</span></p>
  <p class="img-rates">Downloads<span>${E}</span></p></div>
</li>
`}function v(r){return r.map(P).join(`
`)}const f=document.querySelector(".form"),g=f.querySelector(".submit"),R=document.querySelector(".load-more");let n,l;f.addEventListener("input",r=>{l=r.currentTarget.elements["search-text"].value.trim(),l?g.disabled=!1:g.disabled=!0});f.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.currentTarget.elements["search-text"].value.trim(),r.currentTarget.nodeName!="BUTTON"){T(),$(),n=1;try{const t=await y(l,n);L(),S(t)}catch(t){console.error(t)}w(n)}});R.addEventListener("click",async r=>{n+=1;try{const t=await y(l,n);L(),M(t)}catch(t){console.error(t)}A(),w(n)});
//# sourceMappingURL=index.js.map
