import{a as g,i as m,S as M}from"./assets/vendor-BHdvj17y.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=n(t);fetch(t.href,s)}})();let f=1;async function h(e,r){g.defaults.baseURL="https://pixabay.com";const n={key:"51707366-c8695cacd8b805538752cece0",q:`${e}`,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};try{const a=await g.get("/api/",{params:n});f=Math.ceil(a.data.totalHits/n.per_page);const t=a.data.hits;return t&&Array.isArray(t)&&t.length>0?t:m.show({title:"❌",message:"Sorry, there are no images matching <br> your search query. Please try again!",color:"red",position:"topRight",messageColor:"white",titleColor:"white"})}catch(a){m.show({title:"Error",message:a.message})}}const l=document.querySelector(".loader"),d=document.querySelector(".gallery"),L=document.querySelector(".load-more");l&&(l.hidden=!0);const b=new M(".gallery-item a",{captionsData:"alt",captionDelay:250});function T(e){const r=q(e);d.insertAdjacentHTML("afterbegin",r),b.refresh()}function $(e){const r=q(e);d.insertAdjacentHTML("beforeend",r),b.refresh()}function A(){d.innerHTML=""}function w(e){l.hidden=!1,e>1&&l.classList.add("load-more-loader")}function v(){l.hidden=!0}function E(e){e<f?O():f&&(p(),m.info({message:"We're sorry, but you've reached the end of search results.",color:"blue",position:"topRight",messageColor:"black"}))}function B(){let r=d.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r.height*2,left:0,behavior:"smooth"})}function O(){L.classList.add("is-visible")}function p(){L.classList.remove("is-visible")}function P(e){const{webformatURL:r,largeImageURL:n,tags:a,likes:t,views:s,comments:i,downloads:S}=e;return`<li class="gallery-item">
  <a class="gallery-link" href="${n}">
    <img
      class="gallery-image"
      src="${r}"
      alt="${a}"
    />
  </a><div class="stats">
  <p class="img-rates">Likes<span>${t}</span></p>
  <p class="img-rates">Views<span>${s}</span></p>
  <p class="img-rates">Comments<span>${i}</span></p>
  <p class="img-rates">Downloads<span>${S}</span></p></div>
</li>
`}function q(e){return e.map(P).join(`
`)}const c=document.querySelector(".form"),y=c.querySelector(".submit"),R=document.querySelector(".load-more");let o,u;c.addEventListener("input",e=>{u=e.currentTarget.elements["search-text"].value.trim(),u?y.disabled=!1:y.disabled=!0});c.addEventListener("submit",async e=>{if(e.preventDefault(),u=e.currentTarget.elements["search-text"].value.trim(),e.currentTarget.nodeName!="BUTTON"){A(),p(),o=1,w(o);try{const r=await h(u,o);T(r)}catch(r){console.error(r)}v(),E(o),c.reset()}});R.addEventListener("click",async e=>{o+=1,p(),w(o);try{const r=await h(u,o);$(r)}catch(r){console.error(r)}v(),B(),E(o),c.reset()});
//# sourceMappingURL=index.js.map
